export const gamesList: string[] = [
  "The Legend of Zelda: Breath of the Wild",
  "Red Dead Redemption 2",
  "The Witcher 3: Wild Hunt",
  "Fortnite",
  "Super Mario Odyssey",
  "Grand Theft Auto V",
  "Minecraft",
  "Overwatch",
  "Super Smash Bros. Ultimate",
  "FIFA 21",
  "Call of Duty: Modern Warfare",
  "Assassin's Creed Valhalla",
  "Cyberpunk 2077",
  "Destiny 2",
  "Apex Legends",
  "Animal Crossing: New Horizons",
  "God of War",
  "Rainbow Six Siege",
  "Pokémon Sword and Shield",
  "Doom Eternal",
  "Halo Infinite",
  "Sekiro: Shadows Die Twice",
  "Mortal Kombat 11",
  "Borderlands 3",
  "Fornite",
  "Resident Evil Village",
  "Battlefield V",
  "The Last of Us Part II",
  "Marvel's Spider-Man: Miles Morales",
  "Star Wars Jedi: Fallen Order",
  "Fallout 4",
  "Rocket League",
  "The Elder Scrolls V: Skyrim",
  "Horizon Zero Dawn",
  "Genshin Impact",
  "Among Us",
  "Monster Hunter Rise",
  "Cuphead",
  "Nier: Automata",
  "Super Mario Maker 2",
  "Dark Souls III",
  "Persona 5",
  "The Sims 4",
  "Final Fantasy VII Remake",
  "The Outer Worlds",
  "StarCraft II",
  "Diablo III",
  "Battlefield 1",
  "Forza Horizon 4",
  "Call of Duty: Warzone",
  "GTA 5",
  "Forza Motorsport 7",
  "For Honor",
  "Sea of Thieves",
  "Bioshock Infinite",
  "Watch Dogs: Legion",
  "Team Fortress 2",
  "Dota 2",
  "The Division 2",
  "Madden NFL 21",
  "NBA 2K21",
  "Rainbow Six: Siege",
  "Hitman 3",
  "Bloodborne",
  "Resident Evil 2 Remake",
  "Metro Exodus",
  "Far Cry 5",
  "Ghost of Tsushima",
  "The Medium",
  "Control",
  "Dead by Daylight",
  "Street Fighter V",
  "The Sims 3",
  "Shadow of the Tomb Raider",
  "Star Wars Battlefront II",
  "Warframe",
  "Assassin's Creed Odyssey",
  "Death Stranding",
  "World of Warcraft",
  "Cities: Skylines",
  "Fallout 76",
  "Titanfall 2",
  "Stardew Valley",
  "Sims 4",
  "Resident Evil 3 Remake",
  "Doom",
  "Detroit: Become Human",
  "Tom Clancy's The Division",
  "Gears of War 5",
  "Resident Evil 7: Biohazard",
  "Resident Evil 8: Village",
  "Dead Cells",
  "Firewatch",
  "The Witness",
  "Celeste",
  "Undertale",
  "Journey",
  "Terraria",
  "Hades",
  "Limbo",
  "INSIDE",
  "Oxenfree",
  "Ori and the Blind Forest",
  "Outer Wilds",
  "Inside",
  "Machinarium",
  "Dead Space",
  "Mass Effect 2",
  "Mass Effect 3",
  "Star Wars: Knights of the Old Republic",
  "Baldur's Gate II: Shadows of Amn",
  "Half-Life 2",
  "Portal 2",
  "Left 4 Dead 2",
  "Counter-Strike: Global Offensive",
  "Dota 2",
  "Team Fortress 2",
  "Stardew Valley",
  "Terraria",
  "RimWorld",
  "Hollow Knight",
  "Factorio",
  "Celeste",
  "Divinity: Original Sin II",
  "Dead Cells",
  "Subnautica",
  "Oxygen Not Included",
  "Rogue Legacy",
  "Hotline Miami",
  "Hades",
  "FTL: Faster Than Light",
  "Enter the Gungeon",
  "The Binding of Isaac: Rebirth",
  "Cuphead",
  "Nidhogg",
  "Super Meat Boy",
  "Mega Man 11",
  "Shovel Knight",
  "Katana ZERO",
  "Oxenfree",
  "Limbo",
  "INSIDE",
  "Bastion",
  "Transistor",
  "Pyre",
  "What Remains of Edith Finch",
  "Firewatch",
  "Journey",
  "The Stanley Parable",
  "Gris",
  "Night in the Woods",
  "The Witness",
  "Dear Esther",
  "ABZÛ",
  "Everybody's Gone to the Rapture",
  "The Vanishing of Ethan Carter",
  "Virginia",
  "Outer Wilds",
  "The Talos Principle",
  "Papers, Please",
  "Return of the Obra Dinn",
  "Disco Elysium",
  "Her Story",
  "The Wolf Among Us",
  "Telltale's The Walking Dead",
  "Life is Strange",
  "Until Dawn",
  "Heavy Rain",
  "Beyond: Two Souls",
  "Detroit: Become Human",
  "Soma",
  "Amnesia: The Dark Descent",
  "Outlast",
  "Resident Evil 7: Biohazard",
  "Alien: Isolation",
  "Dead Space",
  "Metro 2033",
  "Prey",
  "The Evil Within",
  "Layers of Fear",
  "Observer",
  "Little Nightmares",
  "A Plague Tale: Innocence",
  "Blair Witch",
  "Resident Evil 2 Remake",
  "Control",
  "Death Stranding",
  "The Medium",
  "Hellblade: Senua's Sacrifice",
  "Returnal",
  "The Last Guardian",
  "Prey",
  "Nioh 2",
  "Sekiro: Shadows Die Twice",
  "Demon's Souls",
  "Bloodborne",
  "Dark Souls III",
  "Ghost of Tsushima",
  "Sushi Striker: The Way of Sushido",
  "Cuphead",
  "Donkey Kong Country: Tropical Freeze",
  "Hollow Knight",
  "Celeste",
  "Super Meat Boy",
  "Dead Cells",
  "Stardew Valley",
  "Terraria",
  "Minecraft",
  "RimWorld",
  "Hades",
  "Animal Crossing: New Horizons",
  "Stardew Valley",
  "Undertale",
  "Celeste",
  "Slay the Spire",
  "FTL: Faster Than Light",
  "Into the Breach",
  "Dead Cells",
  "Darkest Dungeon",
  "Frostpunk",
  "Hades",
  "Binding of Isaac",
  "Hotline Miami",
  "Cuphead",
  "Undertale",
  "Celeste",
  "Oxenfree",
  "Firewatch",
  "Journey",
  "INSIDE",
  "Bastion",
  "Transistor",
  "Pyre",
  "Night in the Woods",
  "Limbo",
  "Dear Esther",
  "Virginia",
  "Gris",
  "The Witness",
  "Outer Wilds",
  "Papers, Please",
  "Return of the Obra Dinn",
  "Her Story",
  "The Vanishing of Ethan Carter",
  "What Remains of Edith Finch",
  "Detroit: Become Human",
  "Life is Strange",
  "Until Dawn",
  "Heavy Rain",
  "Beyond: Two Souls",
  "Soma",
  "Outlast",
  "Amnesia: The Dark Descent",
  "The Evil Within",
  "Prey",
  "Resident Evil 7: Biohazard",
  "Alien: Isolation",
  "Metro 2033",
  "Layers of Fear",
  "Observer",
  "A Plague Tale: Innocence",
  "Resident Evil 2 Remake",
  "Control",
  "Death Stranding",
  "The Medium",
  "Hellblade: Senua's Sacrifice",
  "Returnal",
  "The Last Guardian",
  "Prey",
  "Nioh 2",
  "Sekiro: Shadows Die Twice",
  "Demon's Souls",
  "Bloodborne",
  "Dark Souls III",
  "Ghost of Tsushima",
  "Sushi Striker: The Way of Sushido",
  "Cuphead",
  "Donkey Kong Country: Tropical Freeze",
  "Hollow Knight",
  "Celeste",
  "Super Meat Boy",
  "Dead Cells",
  "Stardew Valley",
  "Terraria",
  "Minecraft",
  "RimWorld",
  "Hades",
  "Animal Crossing: New Horizons",
  "Stardew Valley",
  "Undertale",
  "Celeste",
  "Slay the Spire",
  "FTL: Faster Than Light",
  "Into the Breach",
  "Dead Cells",
  "Darkest Dungeon",
  "Frostpunk",
  "Hades",
  "Binding of Isaac",
  "Hotline Miami",
  "Cuphead",
  "Undertale",
  "Celeste",
  "Oxenfree",
  "Firewatch",
  "Journey",
  "INSIDE",
  "Bastion",
  "Transistor",
  "Pyre",
  "Night in the Woods",
  "Limbo",
  "Dear Esther",
  "Virginia",
  "Gris",
  "The Witness",
  "Outer Wilds",
  "Papers, Please",
  "Return of the Obra Dinn",
  "Her Story",
  "The Vanishing of Ethan Carter",
  "What Remains of Edith Finch",
  "Detroit: Become Human",
  "Life is Strange",
  "Until Dawn",
  "Heavy Rain",
  "Beyond: Two Souls",
  "Soma",
  "Outlast",
  "Amnesia: The Dark Descent",
  "The Evil Within",
  "Prey",
  "Resident Evil 7: Biohazard",
  "Alien: Isolation",
  "Metro 2033",
  "Layers of Fear",
  "Observer",
  "A Plague Tale: Innocence",
  "Resident Evil 2 Remake",
  "Control",
  "Death Stranding",
  "The Medium",
  "Hellblade: Senua's Sacrifice",
  "Returnal",
  "The Last Guardian",
  "Prey",
  "Nioh 2",
  "Sekiro: Shadows Die Twice",
  "Demon's Souls",
  "Bloodborne",
  "Dark Souls III",
  "Ghost of Tsushima",
  "Sushi Striker: The Way of Sushido",
  "Cuphead",
  "Donkey Kong Country: Tropical Freeze",
  "Hollow Knight",
  "Celeste",
  "Super Meat Boy",
  "Dead Cells",
  "Stardew Valley",
  "Terraria",
  "Minecraft",
  "RimWorld",
  "Hades",
  "Animal Crossing: New Horizons",
  "Stardew Valley",
  "Undertale",
  "Celeste",
  "Slay the Spire",
  "FTL: Faster Than Light",
  "Into the Breach",
  "Dead Cells",
  "Darkest Dungeon",
  "Frostpunk",
  "Hades",
  "Binding of Isaac",
  "Hotline Miami",
  "Cuphead",
  "Undertale",
  "Celeste",
  "Oxenfree",
  "Firewatch",
  "Journey",
  "INSIDE",
  "Bastion",
  "Transistor",
  "Pyre",
  "Night in the Woods",
  "Limbo",
  "Dear Esther",
  "Virginia",
  "Gris",
  "The Witness",
  "Outer Wilds",
  "Papers, Please",
  "Return of the Obra Dinn",
  "Her Story",
  "The Vanishing of Ethan Carter",
  "What Remains of Edith Finch",
  "Detroit: Become Human",
  "Life is Strange",
  "Until Dawn",
  "Heavy Rain",
  "Beyond: Two Souls",
  "Soma",
  "Outlast",
  "Amnesia: The Dark Descent",
  "The Evil Within",
  "Prey",
  "Resident Evil 7: Biohazard",
  "Alien: Isolation",
  "Metro 2033",
  "Layers of Fear",
  "Observer",
  "A Plague Tale: Innocence",
  "Resident Evil 2 Remake",
  "Control",
  "Death Stranding",
  "The Medium",
  "Hellblade: Senua's Sacrifice",
  "Returnal",
  "The Last Guardian",
  "Prey",
  "Nioh 2",
  "Sekiro: Shadows Die Twice",
  "Demon's Souls",
  "Bloodborne",
  "Dark Souls III",
  "Ghost of Tsushima",
  "Sushi Striker: The Way of Sushido",
  "Cuphead",
  "Donkey Kong Country: Tropical Freeze",
  "Hollow Knight",
  "Celeste",
  "Super Meat Boy",
  "Dead Cells",
  "Stardew Valley",
  "Terraria",
  "Minecraft",
  "RimWorld",
  "Hades",
  "Animal Crossing: New Horizons",
  "Stardew Valley",
  "Undertale",
  "Celeste",
  "Slay the Spire",
  "FTL: Faster Than Light",
  "Into the Breach",
  "Dead Cells",
  "Darkest Dungeon",
  "Frostpunk",
  "Hades",
  "Binding of Isaac",
  "Hotline Miami",
  "Cuphead",
];
